---
abstract: 'match exceptions by class name or regexp'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.013, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Fatal-matchfor
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Test::Fatal::matchfor:
    file: lib/Test/Fatal/matchfor.pm
    version: 0.001
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Test-Fatal-matchfor/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Test-Fatal-matchfor
  homepage: https://metacpan.org/release/Test-Fatal-matchfor
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-test-fatal-matchfor
version: 0.001
